baseURL = "https://anomalia.sk/"
languageCode = "en-us"
title = "We are bottomless repository of magnificent ideas"
googleAnalytics = ""

[params]
    author = "y.06"
    description = ""
    accent = "#CE173C"
    showBorder = false
    font = "Work Sans"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]


[[menu.main]]
    url = "/works/"
    name = "WORKS"
    weight = 2

[[menu.main]]
    url = "/about-us/"
    name = "ABOUT US"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "CONTACT"
    weight = 4

[[menu.icon]]
    url = "https://instagram.com/"
    name = "fa fa-instagram"
    weight = 1

[[menu.icon]]
    url = "https://facebook.com/"
    name = "fa fa-facebook"
    weight = 2